version: "3"
services:
  mongo:
    container_name: mongo-survey-api
    image: mongo:4.4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: survey-api
    image: node:16
    working_dir: /clean-node-survey-api
    restart: always
    command: bash -c "npm install --omit=dev && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-survey-api
    volumes:
      - ./dist:/clean-node-survey-api/dist
      - ./package.json:/clean-node-survey-api/package.json
      - ./package-lock.json:/clean-node-survey-api/package-lock.json
    ports:
      - "3030:3030"
      - "9222:9222"
    links:
      - mongo